/**
 * modified utopia core
 * https://github.com/trys/utopia-core
 */

type UtopiaLabelStyle = 'tailwind' | 'tshirt' | 'utopia'
type UtopiaRelativeTo = 'container' | 'viewport-width' | 'viewport'

export interface UtopiaTypeConfig {
  maxFontSize: number
  maxTypeScale: number
  maxWidth: number
  minFontSize: number
  minTypeScale: number
  minWidth: number
  calculateTypeSize?: (options: {
    fontSize: number
    scale: number
    step: number
    steps: number
  }) => number
  labelStyle?: UtopiaLabelStyle
  negativeSteps?: number
  positiveSteps?: number
  relativeTo?: UtopiaRelativeTo
}

export interface UtopiaStep {
  clamp: string
  label: string
  maxFontSize: number
  minFontSize: number
  step: number
  wcagViolation?:
    | {
        from: number
        to: number
      }
    | undefined
}

export interface UtopiaSpaceConfig {
  maxSize: number
  maxWidth: number
  minSize: number
  minWidth: number
  customSizes?: string[]
  negativeSteps?: number[]
  positiveSteps?: number[]
  relativeTo?: UtopiaRelativeTo
}

export interface UtopiaSize {
  clamp: string
  clampPx: string
  label: string
  maxSize: number
  minSize: number
  multiplier: number
}

export interface UtopiaSpaceScale {
  customPairs: UtopiaSize[]
  oneUpPairs: UtopiaSize[]
  sizes: UtopiaSize[]
}

export interface UtopiaClampsConfig {
  maxWidth: number
  minWidth: number
  pairs: Array<[number, number]>
  relativeTo?: UtopiaRelativeTo
}

export interface UtopiaClampConfig {
  maxSize: number
  maxWidth: number
  minSize: number
  minWidth: number
  relativeTo?: UtopiaRelativeTo
  usePx?: boolean
}

export interface UtopiaClamp {
  clamp: string
  label: string
}

// Helpers

const lerp = (x: number, y: number, a: number) => x * (1 - a) + y * a
const clamp = (a: number, min = 0, max = 1) => Math.min(max, Math.max(min, a))
const invlerp = (x: number, y: number, a: number) => clamp((a - x) / (y - x))
const range = (x1: number, y1: number, x2: number, y2: number, a: number) =>
  lerp(x2, y2, invlerp(x1, y1, a))
const roundValue = (n: number) => Math.round((n + Number.EPSILON) * 10_000) / 10_000
const sortNumberAscending = (a: number, b: number) => Number(a) - Number(b)

// Clamp

export const calculateClamp = ({
  maxSize,
  maxWidth,
  minSize,
  minWidth,
  relativeTo = 'viewport-width',
  usePx = false,
}: UtopiaClampConfig): string => {
  const isNegative = minSize > maxSize
  const min = isNegative ? maxSize : minSize
  const max = isNegative ? minSize : maxSize

  const divider = usePx ? 1 : 16
  const unit = usePx ? 'px' : 'rem'
  const relativeUnits: Record<UtopiaRelativeTo, string> = {
    'container': 'cqi',
    'viewport': 'vi',
    'viewport-width': 'vw',
  }
  const relativeUnit = relativeUnits[relativeTo] ?? relativeUnits.viewport

  const slope = (maxSize / divider - minSize / divider) / (maxWidth / divider - minWidth / divider)
  const intersection = -1 * (minWidth / divider) * slope + minSize / divider
  return `clamp(${roundValue(min / divider)}${unit}, ${roundValue(intersection)}${unit} + ${roundValue(slope * 100)}${relativeUnit}, ${roundValue(max / divider)}${unit})`
}

/**
 * checkWCAG
 * Check if the clamp confirms to WCAG 1.4.4
 * Many thanks to Maxwell Barvian, creator of fluid.style for this calculation
 * {@link https://barvian.me}
 * @returns number[] | undefined
 */
export function checkWCAG({
  max,
  maxWidth,
  min,
  minWidth,
}: {
  max: number
  maxWidth: number
  min: number
  minWidth: number
}): number[] | undefined {
  if (minWidth > maxWidth) {
    // need to flip because our checks assume minWidth < maxWidth
    const oldMinScreen = minWidth
    minWidth = maxWidth
    maxWidth = oldMinScreen

    const oldmin = min
    min = max
    max = oldmin
  }
  const slope = (max - min) / (maxWidth - minWidth)
  const intercept = min - minWidth * slope
  const lh = (5 * min - 2 * intercept) / (2 * slope)
  const rh = (5 * intercept - 2 * max) / (-1 * slope)
  const lh2 = (3 * intercept) / slope

  // this assumes minWidth < maxWidth, hence the flip above
  // These were generated by creating piecewise functions for z5 (the font at 500% zoom in Chrome/Firefox)
  // and 2*z1 (2*the font at 100% zoom; the WCAG requirement), then solving for
  // z5 < 2*z1
  let failRange: number[] | undefined = []
  if (maxWidth < 5 * minWidth) {
    if (minWidth < lh && lh < maxWidth) {
      failRange.push(Math.max(lh, minWidth), maxWidth)
    }
    if (5 * min < 2 * max) {
      failRange.push(maxWidth, 5 * minWidth)
    }
    if (5 * minWidth < rh && rh < 5 * maxWidth) {
      failRange.push(5 * minWidth, Math.min(rh, 5 * maxWidth))
    }
  } else {
    if (minWidth < lh && lh < 5 * minWidth) {
      failRange.push(Math.max(lh, minWidth), 5 * minWidth)
    }
    if (5 * minWidth < lh2 && lh2 < maxWidth) {
      failRange.push(Math.max(lh2, 5 * minWidth), maxWidth)
    }
    if (maxWidth < rh && rh < 5 * maxWidth) {
      failRange.push(maxWidth, Math.min(rh, 5 * maxWidth))
    }
  }

  // Clean up range
  if (failRange.length !== 0) {
    failRange = [failRange[0], failRange[failRange.length - 1]]
    if (Math.abs(failRange[1] - failRange[0]) < 0.1) failRange = undefined // rounding errors, ignore
  }

  return failRange
}

export const calculateClamps = ({
  maxWidth,
  minWidth,
  pairs = [],
  relativeTo,
}: UtopiaClampsConfig): UtopiaClamp[] =>
  pairs.map(([minSize, maxSize]) => ({
    clamp: calculateClamp({ maxSize, maxWidth, minSize, minWidth, relativeTo }),
    clampPx: calculateClamp({ maxSize, maxWidth, minSize, minWidth, relativeTo, usePx: true }),
    label: `${minSize}-${maxSize}`,
  }))

// Type

const calculateTypeSize = (
  config: UtopiaTypeConfig,
  viewport: number,
  step: number,
  steps: number,
): number => {
  const scale = range(
    config.minWidth,
    config.maxWidth,
    config.minTypeScale,
    config.maxTypeScale,
    viewport,
  )
  const fontSize = range(
    config.minWidth,
    config.maxWidth,
    config.minFontSize,
    config.maxFontSize,
    viewport,
  )

  return config.calculateTypeSize !== undefined
    ? config.calculateTypeSize({ fontSize, scale, step, steps })
    : fontSize * Math.pow(scale, step / steps)
}

const mapStepToLabel = (step: number, labelGroup: UtopiaLabelStyle = 'utopia') => {
  if (labelGroup === 'utopia') return step.toString()

  if (step < -2) return `${-1 * (step + 1)}xs`
  if (step === -2) return 'xs'

  if (labelGroup === 'tailwind') {
    if (step === -1) return 'sm'
    if (step === 0) return 'base'
    if (step === 1) return 'lg'
  }

  if (labelGroup === 'tshirt') {
    if (step === -1) return 's'
    if (step === 0) return 'm'
    if (step === 1) return 'l'
  }

  if (step === 2) return 'xl'
  if (step > 2) return `${step - 1}xl`

  return step.toString()
}

const calculateTypeStep = (config: UtopiaTypeConfig, step: number, steps: number): UtopiaStep => {
  const minFontSize = calculateTypeSize(config, config.minWidth, step, steps)
  const maxFontSize = calculateTypeSize(config, config.maxWidth, step, steps)
  const wcag = checkWCAG({
    max: maxFontSize,
    maxWidth: config.maxWidth,
    min: minFontSize,
    minWidth: config.minWidth,
  })

  return {
    clamp: calculateClamp({
      maxSize: maxFontSize,
      maxWidth: config.maxWidth,
      minSize: minFontSize,
      minWidth: config.minWidth,
      relativeTo: config.relativeTo,
    }),
    label: mapStepToLabel(step, config.labelStyle),
    maxFontSize: roundValue(maxFontSize),
    minFontSize: roundValue(minFontSize),
    step,
    wcagViolation:
      Array.isArray(wcag) && wcag.length > 0
        ? {
            from: Math.round(wcag[0]),
            to: Math.round(wcag[1]),
          }
        : undefined,
  }
}

export const calculateTypeScale = (config: UtopiaTypeConfig): UtopiaStep[] => {
  const steps = Math.max(config.positiveSteps ?? 0, config.negativeSteps ?? 0)

  const positiveSteps = Array.from({ length: config.positiveSteps ?? 0 })
    .map((_, index) => calculateTypeStep(config, index + 1, steps))
    .reverse()

  const negativeSteps = Array.from({ length: config.negativeSteps ?? 0 }).map((_, index) =>
    calculateTypeStep(config, -1 * (index + 1), steps),
  )

  return [...positiveSteps, calculateTypeStep(config, 0, 1), ...negativeSteps]
}

// Space

const calculateSpaceSize = (
  config: UtopiaSpaceConfig,
  multiplier: number,
  step: number,
): UtopiaSize => {
  const minSize = Math.round(config.minSize * multiplier)
  const maxSize = Math.round(config.maxSize * multiplier)

  let label = 'S'
  if (step === 1) {
    label = 'M'
  } else if (step === 2) {
    label = 'L'
  } else if (step === 3) {
    label = 'XL'
  } else if (step > 3) {
    label = `${step - 2}XL`
  } else if (step === -1) {
    label = 'XS'
  } else if (step < 0) {
    label = `${Math.abs(step)}XS`
  }

  return {
    clamp: calculateClamp({
      maxSize,
      maxWidth: config.maxWidth,
      minSize,
      minWidth: config.minWidth,
      relativeTo: config.relativeTo,
    }),
    clampPx: calculateClamp({
      maxSize,
      maxWidth: config.maxWidth,
      minSize,
      minWidth: config.minWidth,
      relativeTo: config.relativeTo,
      usePx: true,
    }),
    label: label.toLowerCase(),
    maxSize: roundValue(maxSize),
    minSize: roundValue(minSize),
    multiplier,
  }
}

const calculateOneUpPairs = (config: UtopiaSpaceConfig, sizes: UtopiaSize[]): UtopiaSize[] =>
  [...sizes.reverse()]
    .map((size, index, array) => {
      if (index === 0) return undefined
      const previous = array[index - 1]
      return {
        clamp: calculateClamp({
          maxSize: size.maxSize,
          maxWidth: config.maxWidth,
          minSize: previous.minSize,
          minWidth: config.minWidth,
          relativeTo: config.relativeTo,
        }),
        clampPx: calculateClamp({
          maxSize: size.maxSize,
          maxWidth: config.maxWidth,
          minSize: previous.minSize,
          minWidth: config.minWidth,
          relativeTo: config.relativeTo,
          usePx: true,
        }),
        label: `${previous.label}-${size.label}`,
        maxSize: size.maxSize,
        minSize: previous.minSize,
      }
    })
    .filter((size): size is UtopiaSize => size !== undefined)

const calculateCustomPairs = (config: UtopiaSpaceConfig, sizes: UtopiaSize[]): UtopiaSize[] =>
  (config.customSizes ?? [])
    .map((label) => {
      const [keyA, keyB] = label.split('-')
      // eslint-disable-next-line typescript/strict-boolean-expressions
      if (!keyA || !keyB) return undefined

      const a = sizes.find((x) => x.label === keyA)
      const b = sizes.find((x) => x.label === keyB)
      // eslint-disable-next-line typescript/strict-boolean-expressions
      if (!a || !b) return undefined

      return {
        clamp: calculateClamp({
          maxSize: b.maxSize,
          maxWidth: config.maxWidth,
          minSize: a.minSize,
          minWidth: config.minWidth,
          relativeTo: config.relativeTo,
        }),
        clampPx: calculateClamp({
          maxSize: b.maxSize,
          maxWidth: config.maxWidth,
          minSize: a.minSize,
          minWidth: config.minWidth,
          relativeTo: config.relativeTo,
          usePx: true,
        }),
        label: `${keyA}-${keyB}`,
        maxSize: b.maxSize,
        minSize: a.minSize,
      }
    })
    .filter((size): size is UtopiaSize => size !== undefined)

export const calculateSpaceScale = (config: UtopiaSpaceConfig): UtopiaSpaceScale => {
  const positiveSteps = [...(config.positiveSteps ?? [])]
    .sort(sortNumberAscending)
    .map((multiplier, index) => calculateSpaceSize(config, multiplier, index + 1))
    .reverse()

  const negativeSteps = [...(config.negativeSteps ?? [])]
    .sort(sortNumberAscending)
    .reverse()
    .map((multiplier, index) => calculateSpaceSize(config, multiplier, -1 * (index + 1)))

  const sizes = [...positiveSteps, calculateSpaceSize(config, 1, 0), ...negativeSteps]

  const oneUpPairs = calculateOneUpPairs(config, sizes)
  const customPairs = calculateCustomPairs(config, sizes)

  return {
    customPairs,
    oneUpPairs,
    sizes,
  }
}

// TODO: snap to grid

// sans-serif-1/2
// sans-serif-

export const typeScaleToString = (config: { prefix?: string } & UtopiaTypeConfig): string => {
  const scales = calculateTypeScale(config)
  const prefix = config.prefix ?? 'type'

  const wcagViolations = scales
    .map((value) => value.wcagViolation)
    .filter((value) => value !== undefined)

  if (wcagViolations.length !== 0) {
    throw new Error(
      `WCAG 1.4.4 violation(s): ${wcagViolations.map((value) => `${value.from}-${value.to}`).join(', ')}`,
    )
  }

  return [
    ':root {',
    ...scales.flatMap((value) => [
      `  /* ${value.label}: ${value.minFontSize}px → ${value.maxFontSize}px */`,
      `  --${prefix}-${value.label}: ${value.clamp};`,
    ]),
    '}',
  ].join('\n')
}

// const result = typeScaleToString({
//   labelStyle: 'tshirt',
//   maxFontSize: 20,
//   maxTypeScale: 1.25,
//   maxWidth: 1240,
//   minFontSize: 18,
//   minTypeScale: 1.2,
//   minWidth: 320,
//   negativeSteps: 3,
//   positiveSteps: 5,
// })
//
// console.log(result)
