import type { Rule } from '@unocss/core'
import type { Theme } from '@unocss/preset-wind4/theme'

// TODO:
//
// accents
// backgroundStyles
// bgColors
// borders
// boxShadows
// carets
// divides
// filters
// fonts
// outline
// placeholders
// rings
// svgUtilities
// textDecorations
// textShadows
// textStrokes
// fontStyles

import {
  accessibility,
  alignments,
  animations,
  appearance,
  appearances,
  aspectRatio,
  backgroundBlendModes,
  boxSizing,
  breaks,
  colorScheme,
  columns,
  container,
  containerParent,
  contains,
  contentVisibility,
  contents,
  cssProperty,
  cssVariables,
  cursors,
  displays,
  dynamicViewportHeight,
  flex,
  flexGridJustifiesAlignments,
  floats,
  fontSmoothings,
  fontVariantNumeric,
  gaps,
  grids,
  hyphens,
  imageRenderings,
  insets,
  isolations,
  justifies,
  lineClamps,
  listStyle,
  margins,
  mixBlendModes,
  objectPositions,
  opacity,
  orders,
  overflows,
  overscrolls,
  paddings,
  placements,
  pointerEvents,
  positions,
  questionMark,
  resizes,
  screenReadersAccess,
  scrollBehaviors,
  scrolls,
  sizes,
  spaces,
  tabSizes,
  tables,
  textAligns,
  textIndents,
  textOverflows,
  textTransforms,
  textWraps,
  touchActions,
  transforms,
  transitions,
  userSelects,
  verticalAligns,
  viewTransition,
  whitespaces,
  willChange,
  writingModes,
  writingOrientations,
  zIndexes,
} from '@unocss/preset-wind4/rules'

export const rules: Array<Rule<Theme>> = [
  accessibility,
  alignments,
  animations,
  appearance,
  appearances,
  aspectRatio,
  backgroundBlendModes,
  boxSizing,
  breaks,
  colorScheme,
  columns,
  container,
  containerParent,
  contains,
  contentVisibility,
  contents,
  cssProperty,
  cssVariables,
  cursors,
  displays,
  dynamicViewportHeight,
  flex,
  flexGridJustifiesAlignments,
  floats,
  fontSmoothings,
  fontVariantNumeric,
  gaps,
  grids,
  hyphens,
  imageRenderings,
  insets,
  isolations,
  justifies,
  lineClamps,
  listStyle,
  margins,
  mixBlendModes,
  objectPositions,
  opacity,
  orders,
  overflows,
  overscrolls,
  paddings,
  placements,
  pointerEvents,
  positions,
  questionMark,
  resizes,
  screenReadersAccess,
  scrollBehaviors,
  scrolls,
  sizes,
  spaces,
  tabSizes,
  tables,
  textAligns,
  textIndents,
  textOverflows,
  textTransforms,
  textWraps,
  touchActions,
  transforms,
  transitions,
  userSelects,
  verticalAligns,
  viewTransition,
  whitespaces,
  willChange,
  writingModes,
  writingOrientations,
  zIndexes,
].flat()
